[build-system]
requires = ["setuptools>=77.0.3", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "copilotix"
dynamic = ["version"]
license = "LicenseRef-MinerU-Open-Source-License"
license-files = ["LICENSE.md"]
description = "A VLM document parsing tool for converting PDF and images into Markdown and JSON"
readme = "README.md"
requires-python = ">=3.10,<3.14"
keywords = [
    "copilotix",
    "magic-pdf",
    "document-parsing",
    "document-understanding",
    "pdf",
    "markdown",
    "ocr",
    "vlm",
    "multimodal",
]
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
dependencies = [
    "click>=8.1.7",
    "loguru>=0.7.2",
    "numpy>=1.21.6",
    "tqdm>=4.67.1",
    "requests",
    "httpx",
    "pillow>=11.0.0",
    "pypdfium2>=4.30.0,<6.0.0",
    "pypdf>=5.6.0",
    "reportlab",
    "json-repair>=0.46.2",
    "opencv-python>=4.11.0.86",
    "fast-langdetect>=0.2.3,<0.3.0",
    "openai>=1.70.0,<3",
    "beautifulsoup4>=4.13.5,<5",
    "magika>=0.6.2,<1.1.0",
    "mineru-vl-utils>=1.0.5,<2",
    "fastapi",
    "python-multipart",
    "uvicorn",
]

[project.optional-dependencies]
test = [
    "copilotix[core]",
    "pytest",
    "pytest-cov",
    "coverage",
    "fuzzywuzzy",
    "tomli; python_version < '3.11'",
]
s3 = [
    "boto3>=1.28.43",
]
gradio = [
    "gradio>=5.49.1,!=6.0.0,!=6.0.1,!=6.0.2,!=6.1.0,!=6.2.0,!=6.3.0,!=6.4.0,!=6.5.0,!=6.5.1,!=6.6.0,!=6.7.0,<6.9.0",
    "gradio-pdf>=0.0.22",
]
core = [
    "copilotix[gradio]",
]
all = [
    "copilotix[core]",
    "copilotix[s3]",
]

[project.urls]
homepage = "https://github.com/Kumiko-kmk/Copilotix"
documentation = "https://github.com/Kumiko-kmk/Copilotix/tree/master/docs"
repository = "https://github.com/Kumiko-kmk/Copilotix"
issues = "https://github.com/Kumiko-kmk/Copilotix/issues"
License = "https://github.com/Kumiko-kmk/Copilotix/blob/master/LICENSE.md"

[project.scripts]
copilotix = "copilotix.cli.client:main"
copilotix-api = "copilotix.cli.fast_api:main"
copilotix-router = "copilotix.cli.router:main"
copilotix-gradio = "copilotix.cli.gradio_app:main"

[tool.setuptools.dynamic]
version = { attr = "copilotix.version.__version__" }

[tool.setuptools.packages.find]
include = ["copilotix*"]
namespaces = false

[tool.setuptools.package-data]
"copilotix" = ["resources/**"]

[tool.setuptools]
include-package-data = true
zip-safe = false

[tool.pytest.ini_options]
addopts = "-s --cov=copilotix --cov-report html"

[tool.coverage.run]
command_line = "-m pytest tests/unittest/test_e2e.py"
source = ["copilotix/"]
omit = [
    "*/gradio_app.py",
    "*/fast_api.py",
    "*/cli/client.py",
    "*/cli_parser.py",
]

[tool.coverage.html]
directory = "htmlcov"

[tool.coverage.report]
exclude_also = [
    'def __repr__',
    'if self.debug:',
    'if settings.DEBUG',
    'raise AssertionError',
    'raise NotImplementedError',
    'if 0:',
    'if __name__ == .__main__.:',
    'if TYPE_CHECKING:',
    'class .*\bProtocol\):',
    '@(abc\.)?abstractmethod',
]

[tool.ruff]
line-length = 128

[tool.ruff.lint]
select = ["C", "E", "F", "W", "ANN"]
ignore = ["C901", "ANN204", "ANN401"]
